### PR TITLE
Making the vagrant VM disable swap for k8s 1.8 

### PR DESCRIPTION
**Pull request by dragoonis**

### CODE REVIEW

**Comment by dkoshkin** [comment]
As part of this PR the option should be removed from the plan file. 
https://github.com/apprenda/kismatic-provision/blob/master/provision/vagrant/planfile.go#L132

**Comment by swade1987** [comment]
@dkoshkin agreed @dragoonis you able to make that change?

**Comment by swade1987** [comment]
LGTM!

**Comment by dragoonis** [comment]
@dkoshkin pushed the tweak - don't know how to test it but hope it looks like what you wanted

**Comment by dkoshkin** [comment]
The options should be similar as the other options:
```
  kubelet:
    option_overrides: {}
```

Once you made the change Ill test.

**Comment by dragoonis** [comment]
@dkoshkin done.

**Comment by dkoshkin** [comment]
Tested it and its looking good, thanks!

**Pull request merged**
