### PR TITLE
Add provision support for Ingress

### PR DESCRIPTION
**Pull request by dasmb**
Kismatic 1.1 will add support for managing Ingress nodes. This is a useful way to access K8s services from outside of a cluster.

Basic support for Ingress has been added to all new clusters built with Provision. For now, the first Worker in any cluster is also used as an Ingress host.

Ingress hosts expose an HTTP proxy (we use a contained Nginx) along with a controller to reconfigure them. This adds a little extra responsibility to the most basic clusters but we think it's worth it.

### CODE REVIEW

**Comment by dkoshkin** [comment]
It looks like you are missing the option in the CLI for the number of ingress nodes.

**Comment by dasmb** [comment]
There currently isn't a way to control ingress node count -- I allow for one ingress node, always the first worker and always schedulable (available to host other workloads).

Introducing specialized workers is gonna be tricky and might be outside the scope of a "make me a full featured demo fast" tool.

**Comment by dkoshkin** [comment]
I was thinking of provisioning a separate node for ingress (then a separate for storage). Defaulting to running the ingress on the same node doesn't follow the message we are providing in Kismatic.

Seems like having a demo of an ingress in a DMZ or a way to have more sophisticated demos might be useful. 

Maybe there could be another cluster mode of 1/1/2 to cover the "demo fast" scenario.

**Comment by dasmb** [comment]
For now, Provision's role is to make development & demoing fast. More complex scenarios (such as anything dealing with the complexity of workers that have different capabilities from each other) is something we want to be cautious adding.

**Pull request merged**
