### PR TITLE
Openstack branch

### PR DESCRIPTION
**Pull request by sashajeltuhin**
Add support to orchestrate k8s cluster on Openstack
The provisioning process on Openstack starts with creating an installer node. This node downloads all the necessary installation packages, starts a local web server (runs in Docker) and launches the requested nodes for the Kubernetes cluster via Openstack APIs. As the cluster members come online and initialize, they report back to the installer node. Once all the requested nodes are up, the installer pushes the required ssh keys to each node and starts the installation of the Kubernetes cluster. At the end of the installation, the Ingress node is assigned a floating IP (if requested) to provide access to future workloads from the outside.
Due to this approach, I had to put main.go into a separate folder folder structure. The package can now be invoked by the web server (used by the Openstack orchestrator) in addition to the command line. Hence the two sibling folders for main under the Exec folder: one for the command line and the other for the webs server.

### CODE REVIEW

**Comment by alexbrand** [comment]
I am not very familiar with OpenStack, but I am not quite understanding why there's the need for an HTTP server here. I think this is a blocker for this PR. 

The provisioner is responsible for standing up infrastructure, but _not_ running `./kismatic install apply`.  In other words, I would expect the OpenStack provisioner to use the OpenStack API to provision machines, and then generate a plan file with the list of machines. The generated plan file can then be used to run kismatic.

I also think it might be better to pick up an existing OpenStack library, such as https://github.com/rackspace/gophercloud, instead of maintaining our own.

**Comment by sashajeltuhin** [comment]
The reason for the HTTP server is for the async install. When you run from the command line you do not have to wait for the servers to come up (which may take 2-5 mins). The installation is self-sufficient. As an enhancement, it can notify the user of the completion.
What's is the reasoning for not running the install after the nodes are provisioned and the plan generated? Wouldn't it be convenient to have the cluster fully prepared for use? I agree with the 3rd party lib for openstack - it may be a better option. I already had an implementation available.

**Comment by dasmb** [comment]
Callbacks are cool, but inherently unreliable in an any context where network security policies are in play.  A tool that requires a firewall entry be opened up for an operator's machine isn't nearly as usable as one that exclusively acts as an http(s) client. What's more, important provisioning matters like detecting a crashed OpenStack service or the need to retry a rejected request are made more difficult by inverting the responsibility to a callback layer.

You're also likely to find that the signal represented by the callback is insufficient for determining the readiness of the underlying infrastructure -- specifically, that machines are marked "available" before the services required for provisioning are available (with ssh/winrm access being the most common manifestation of the problem).

This is why our other provisioners (AWS & Packet) use status checks with retries or long polling to detect uptime of services, and a subsequent SSH 'upness' test to guarantee that machines are not just online, but ready for kismatic to run. Failing to perform this check is likely to result in a failed cluster install.

As for not running the installer immediately after provisioning, this is primarily a choice we made to allow a cluster operator the chance to modify the cluster "plan" file output by the provision tool prior to running Kismatic. There are lots of interesting options in there and the goal of this provision tool is simply to make it easier to start experimenting with them.

I also generally prefer not hiding the important production tool (kismatic) behind the training tool (provision). Someday that kismatic command is going to fail and the operator will need to step through triage of a cluster...it's important that the operator knows that the tool exists and what it's responsible for.

**Comment by sashajeltuhin** [comment]
In this implementation the callback layer sits next to the cluster. It is handled by the node that is spun up in the very beginning of the provisioning. The “callback” server on this node downloads KET packages, creates the keys and spins up the other nodes that will house the actual cluster. The post-init scripts (user data) control the preparation of each node, validate its “readiness” and then report the status to the installer, that runs the http server to receive the messages from the cluster nodes. When each of the requested nodes is fully prepared, it calls back to the installer to report its state. If something goes wrong, the error is communicated to the installer or the installer never hears from the failed nodes. In any case, the KET installation will not start, if the nodes are node ready. Once all the requested nodes have reported success back to the installer, it builds the plan using the data collected from the operator and the necessary information received from the cluster nodes. Finally, it kicks off the KET installation and assigns a floating IP to the Ingress node if so desired so that the workloads can be accessed from the outside. In this entire process, the operator, the person who requested the install, and his machine is out of the picture. The operator only needs to have access to the Openstack API server (open or via VPN) to initiate the otherwise completely asynchronous process. The entire callback mechanism does not hinge on the accessibility to the operator box, it is self-sufficient. The paradigm here is similar to CloudFormation or HEAT, which are based on internal, self-sufficient callback process independent of the operator who initiated the process. With that in mind, callbacks are fairly reliable, as all nodes involved, including the callback server are orchestrated on the same subnet and attached to the same security group (firewall rules). Due to post-init scripts, the reliability of the “readiness” is also higher than that of the standard API check, whether the instance is “up”. The scripts ensure the availability and the proper configuration of the necessary services before firing the callback. Sure, many things can go wrong, the post-init service may not fire or hang, but in either case, the installer will never hear from the node and eventually deem it as faulty or will get an error response. The KET install will only start when all the nodes have reported success to the installer. The operator can check the status of the process by accessing the installer node (over any preferred method) and in case of errors restart the process from scratch or the point of failure. Another purpose of the “callback node” is to be a base and a central point for working with the cluster. Kubectl is installed on that node as a part of the orchestration. The operator(s) could also use this sever to grow the cluster (adding worker nodes, etc.).
My objective with this orchestrator is to bring partner attention to KET as a key tool to install and grow k8s clusters. For example, encourage the partners to contribute and use KET as a foundation of Kubernetes orchestration by their CMP tools. Hence the unattended automated, KET installation, and this non-blocking implementation. I appreciate your vision of the Kismatic provisioner as a training tool and the reasoning behind your implementation choice. I understand that the differences between our approaches and objectives may not be clearly reconcilable. However, taking your approach a step further may not necessarily contradict your original intent. The user of the provisioner can be given an option (via yet another command line flag) to pause before running KET installer in order to play with the plan file for educational, verification or other purposes. To me, however, the ultimate goal of the user is to get to a functional Kubernetes cluster. The user can learn about the plan file from the repo. All the pertinent and meaningful variables of the plan can be collected from the user as command line options or as a Q & A before the orchestration.
 The reason for the fully automated unattended installation in this implementation is not to “hide KET”. It is simply for convenience and portability into partner products. Like I said, we want to make KET a household item in the Kubernetes products/initiatives of our strategic partners.

**Comment by alexbrand** [comment]
Thanks for the detail here @sashajeltuhin. Having OpenStack support in kismatic-provision is interesting to me. How do you feel about implementing a simpler provisioner that just creates the machines and generates the plan file? This could then be leveraged by another tool to achieve the one-click provision+KET install you describe in the comment above.

**Comment by sashajeltuhin** [comment]
Sure. I am tied up for the next 2 weeks, but can take a stab afterwards.

**Pull request closed without merging**
